import {DrawList} from '../../packages/thlib/src/render.js';
import {AnmBank} from '../../games/touhou20/src/anm.js';
import {Th20LaserField} from '../../games/touhou20/src/lasers.js';
import {th20BulletCommand} from '../../games/touhou20/src/bullets.js';
const read=path=>JSON.parse(tsstg.readText(path));
const field=new Th20LaserField({bank:new AnmBank(read('games/touhou20/assets/anm/bullet.json'),{loadTexture:(...args)=>tsstg.loadTexture(...args)}),styles:read('games/touhou20/assets/bullet-styles.json').styles});
field.spawnStraight({x:-150,y:60,angle:.15,type:0,color:1,width:20,length:250,initialLength:80,speed:2,lengthLimit:400});
field.spawnInfinite({x:-150,y:180,angle:-.1,type:16,color:6,width:28,length:300,delay:10,grow:20,sustain:180,shrink:30});
field.spawnCurve({x:-120,y:280,type:0,color:4,width:22,speed:2,count:110,time:20,commands:[th20BulletCommand(3,{floats:[.01,.04],ints:[90,10]})]});
const draw=new DrawList();let frame=0;
globalThis.__tsstg_game={update(){field.update();frame++;},render(){draw.reset().clear(0x141925ff);field.draw(draw);return draw.commands;},snapshot(){return {frame,...field.snapshot()};}};
