if(NOT DEFINED TEST_CASE)
  set(TEST_CASE import)
endif()
if(NOT TEST_CASE MATCHES "^(import|old-subpath|alias-escape|project-escape|library-escape)$")
  message(FATAL_ERROR "Unknown external project test: ${TEST_CASE}")
endif()
set(case_root "${BINARY_ROOT}/native-external-project-${TEST_CASE}")
set(project "${case_root}/project")
file(MAKE_DIRECTORY "${project}/node_modules/@ts-stg")
file(COPY "${SOURCE_ROOT}/native/tests/external-project/" DESTINATION "${project}")
file(WRITE "${case_root}/outside-module.js" "export const escaped = true;\n")

if(TEST_CASE STREQUAL library-escape)
  # A selected library's relative imports must remain inside its own src root,
  # even when the escaped file would otherwise be within the game's root.
  file(MAKE_DIRECTORY "${project}/packages/thlib/src")
  file(WRITE "${project}/packages/thlib/src/index.js" "import '../outside-module.js';\n")
  file(WRITE "${project}/packages/thlib/outside-module.js" "export const escaped = true;\n")
  file(WRITE "${project}/library-escape.js" "import '@ts-stg/thlib';\n")
else()
  set(library "${project}/node_modules/@ts-stg/thlib")
  string(REPLACE "'" "''" escaped_library "${library}")
  if(NOT EXISTS "${library}")
    file(CREATE_LINK "${SOURCE_ROOT}/packages/thlib" "${library}" SYMBOLIC RESULT link_result)
    if(link_result AND WIN32)
      # Directory junctions do not need developer mode or symlink privileges.
      string(REPLACE "'" "''" escaped_source "${SOURCE_ROOT}/packages/thlib")
      execute_process(COMMAND powershell -NoProfile -NonInteractive -Command
        "New-Item -ItemType Junction -Path '${escaped_library}' -Target '${escaped_source}' | Out-Null"
        RESULT_VARIABLE link_result OUTPUT_QUIET ERROR_QUIET)
    endif()
    if(link_result)
      file(COPY "${SOURCE_ROOT}/packages/thlib/" DESTINATION "${library}")
    endif()
  endif()
  file(REAL_PATH "${library}" canonical_library)
  file(REAL_PATH "${SOURCE_ROOT}/packages/thlib" canonical_source)
  set(library_is_link FALSE)
  if(IS_SYMLINK "${library}" OR canonical_library STREQUAL canonical_source)
    set(library_is_link TRUE)
  elseif(WIN32)
    execute_process(COMMAND powershell -NoProfile -NonInteractive -Command
      "[bool]((Get-Item -LiteralPath '${escaped_library}').Attributes -band [System.IO.FileAttributes]::ReparsePoint)"
      OUTPUT_VARIABLE linked_output OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(linked_output STREQUAL "True")
      set(library_is_link TRUE)
    endif()
  endif()
  if(library_is_link)
    file(READ "${project}/main.js" fixture)
    file(WRITE "${project}/main.js" "globalThis.testLibraryIsSymlink = true;\n${fixture}")
  else()
    # Refresh copied dependencies without recursively deleting directories.
    file(COPY "${SOURCE_ROOT}/packages/thlib/" DESTINATION "${library}")
  endif()
endif()

if(TEST_CASE STREQUAL import)
  set(entry main.js)
else()
  set(entry "${TEST_CASE}.js")
endif()
set(backend_args)
if(DEFINED BACKEND)
  list(APPEND backend_args --backend "${BACKEND}")
endif()
execute_process(COMMAND "${HOST_EXECUTABLE}" "${entry}" --root "${project}" ${backend_args} --headless --frames 1
  --snapshot "${project}/snapshot.json" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(TEST_CASE STREQUAL import)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "External project failed: ${output}\n${error}")
  endif()
  file(READ "${project}/snapshot.json" snapshot)
  if(NOT snapshot MATCHES "\"imported\":true" OR NOT snapshot MATCHES "\"businessRelative\":true" OR NOT snapshot MATCHES "\"position\":22")
    message(FATAL_ERROR "External project snapshot mismatch: ${snapshot}")
  endif()
else()
  if(result EQUAL 0)
    message(FATAL_ERROR "External project boundary incorrectly allowed ${TEST_CASE}")
  endif()
  if(TEST_CASE STREQUAL old-subpath OR TEST_CASE STREQUAL alias-escape)
    set(expected "Unsupported module import")
  else()
    set(expected "Path escapes the permitted root")
  endif()
  if(NOT error MATCHES "${expected}")
    message(FATAL_ERROR "${TEST_CASE} failed for an unexpected reason: ${output}\n${error}")
  endif()
endif()
